import Menu from "@/components/Menu/Menu";
import Navbar from "@/components/Navbar";
import { BsTelephoneFill } from "react-icons/bs";
import { FaMobileAlt, FaMapPin } from "react-icons/fa";

import Head from "next/head";
import { BiUserPlus, BiX, BiCheck, BiHide } from "react-icons/bi";
import Table from "@/components/table";
import Form from "@/components/form";
import { deleteUser, getUsers } from "@/lib/helper";
import { toggleChangeAction, deleteAction } from "@/redux/reducer";
import { useSelector, useDispatch } from "react-redux";
import { useQueryClient } from "react-query";
import MenuSpecials from "@/components/Menu/MenuSpecials";
import MenuOriginals from "@/components/Menu/MenuOriginals";
import MenuFuture from "@/components/Menu/MenuFuture";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const queryclient = useQueryClient();

  const dispatch = useDispatch();

  const handler = () => {
    dispatch(toggleChangeAction());
  };

  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery("users", getUsers);
      dispatch(deleteAction(null));
    }
  };

  const canclehandler = async () => {
    console.log("cancel");
    dispatch(deleteAction(null));
  };

  function getToday() {
    return new Date().getDay();
  }

  const dayToday = getToday();

  return (
    <>
      <Head>
        <title>Lindenhof Pätz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-600 text-stone-300">
        <Navbar />
        <div className="flex flex-col py-16 items-center">
          <MenuSpecials />
          <MenuOriginals />
          <MenuFuture />
        </div>

        <div className="flex px-3 justify-center bg-slate-700 text-stone-400">
          <div className="grid grid-cols-2 mt-10 w-[800px]">
            <div className=" ">
              <h2 className="text-2xl max-sm:text-lg uppercase ps-1 border-l-2 border-slate-600 mb-4">
                Contact
              </h2>
              <ul className="px-2 leading-8 max-sm:text-sm max-sm:leading-8">
                <li className="mx-2 flex flex-row items-center gap-2">
                  <div>
                    <a
                      href={`tel:+49 337 636 3360`}
                      rel="nofollow noreferrer noopener"
                    >
                      <BsTelephoneFill className="hover:scale-150 hover:fill-stone-300" />
                    </a>
                  </div>
                  <div>+49 337 636 3360</div>
                </li>
                <li className="mx-2 flex flex-row items-center gap-2">
                  <a
                    href={`tel:+49 174 807 6935`}
                    rel="nofollow noreferrer noopener"
                  >
                    <FaMobileAlt className="hover:scale-150 hover:fill-stone-300" />
                  </a>
                  <div>+49 174 807 6935</div>
                </li>
                <li className="mx-2 flex flex-row items-center gap-2">
                  <a
                    href="https://maps.google.com/maps?ll=52.226494,13.657365&z=14&t=m&hl=en&gl=DE&mapclient=embed&cid=3786600781970887142"
                    rel="nofollow noreferrer noopener"
                  >
                    <FaMapPin className="hover:scale-150 hover:fill-stone-300" />
                  </a>
                  <div className="max-sm:leading-4">
                    Lindenstraße 4, 15741 Bestensee
                  </div>
                </li>
              </ul>
            </div>
            {/* <OpenTimes /> */}
            {/* <div className="my-2">
            <h2 className="text-2xl max-sm:text-lg uppercase ps-1 border-l-2 border-slate-600 mb-4">
              Opening Hours
            </h2>
            <div className="text-slate-500 px-2 leading-8 max-sm:text-sm">
              <ul className="px-2 leading-8 max-sm:text-sm max-sm:leading-8">
                {openHours.map((today) => {
                  return (
                    <li
                      key={today.id}
                      className={
                        dayToday === today.dayasint
                          ? "text-stone-300 border-b border-slate-600"
                          : "border-b border-slate-600"
                      }
                    >
                      {dayToday === today.dayasint ? "Heute" : today.day}
                      <span className="float-right">{today.times}</span>
                    </li>
                  );
                })}
              </ul>
            </div>
          </div> */}
            {/* END <OpenTimes /> */}
            {/* <OpenTimes /> */}
            <div className="">
              <h2 className="text-2xl max-sm:text-lg uppercase ps-1 border-l-2 border-slate-600 mb-4">
                Opening Hours
              </h2>
              <ul className="text-slate-500 px-2 leading-8 max-sm:text-sm">
                <li
                  className={
                    dayToday === 0
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 0 ? "Heute" : "Sonntag"}
                  <span className="float-right">10:00-20:00</span>
                </li>
                <li
                  className={
                    dayToday === 1
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 1 ? "Heute" : "Montag"}
                  <span className="float-right">Geschlossen</span>
                </li>
                <li
                  className={
                    dayToday === 2
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 2 ? "Heute" : "Dienstag"}
                  <span className="float-right">Geschlossen</span>
                </li>
                <li
                  className={
                    dayToday === 3
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 3 ? "Heute" : "Mittwoch"}
                  <span className="float-right">Geschlossen</span>
                </li>
                <li
                  className={
                    dayToday === 4
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 4 ? "Heute" : "Donnerstag"}
                  <span className="float-right">16:00-22:00</span>
                </li>
                <li
                  className={
                    dayToday === 5
                      ? "text-stone-300 border-b border-slate-600"
                      : "border-b border-slate-600"
                  }
                >
                  {dayToday === 5 ? "Heute" : "Freitag"}
                  <span className="float-right">16:00-23:30</span>
                </li>
                <li
                  className={
                    dayToday === 6
                      ? "text-stone-300 border-b border-slate-600 mb-2"
                      : "border-b border-slate-600 mb-2"
                  }
                >
                  {dayToday === 6 ? "Heute" : "Samstag"}
                  <span className="float-right">10:00-23:30</span>
                </li>
              </ul>
            </div>{" "}
          </div>
        </div>

        <footer>
          <div className="mx-4 pb-4 flex justify-center md:mb-0 ">
            <iframe
              width="100%"
              height={240}
              className="rounded grayscale backdrop-blur-sm bg-black/25"
              title="location map"
              src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6912.749519168954!2d13.65194608249894!3d52.22474487266107!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47a8166bd79f1dd1%3A0x348cb559539751e6!2sLindenhof%20P%C3%A4tz!5e0!3m2!1sen!2sde!4v1676908879463!5m2!1sen!2sde"
              loading="lazy"
            ></iframe>
          </div>
        </footer>
      </main>
    </>
  );
}
